import Head from "next/head";
import HeaderComponent from "../components/Header";
import { useState } from "react";
import WineCard from "../components/WineCard/WineCard";
import { HiChevronRight, HiChevronLeft } from "react-icons/hi";
import { Button } from "../components/ChangePageButton/styles";
import Loading from "../components/Loading/index";

import Radio from "@mui/material/Radio";
import RadioGroup from "@mui/material/RadioGroup";
import FormControlLabel from "@mui/material/FormControlLabel";
import FormControl from "@mui/material/FormControl";

import {
  Container,
  WineContainer,
  FilterContainer,
  ButtonsContainer,
  PageContainer,
  NumberPage,
  NumberOfProducts,
  Cards,
  FormLabel,
  ErrorTextContainer,
  ErrorText,
  Highlight,
} from "../styles/HomeStyles";
import { useWineItems } from "../hooks/queries";
import { Response } from "../services/types";

const limit = 9;

const Home = (): JSX.Element => {
  const [filter, setFilter] = useState("");
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");

  const { data, status } = useWineItems({ filter, limit, name: search, page });

  const getNextPage = () => {
    if (data?.totalPages === page) {
      return;
    }
    setPage(page + 1);
  };

  const getPreviousPage = () => {
    if (page === 1) {
    }
    setPage(page - 1);
  };

  const onChangeSearchText = (text: string) => {
    setSearch(text);
  };

  return (
    <Container>
      <Head>
        <title>Wines</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <HeaderComponent
        searchText={search}
        onChangeSearchText={onChangeSearchText}
      />

      {(status === "loading" || status === "idle") && (
        <div>
          <h2>Loading...</h2>
          <Loading />
        </div>
      )}

      {status === "error" && (
        <div className="message">
          <h3>Erro</h3>
        </div>
      )}

      {status === "success" && (
        <main>
          <FilterContainer>
            <h2>Refine sua busca</h2>
            <FormControl component="fieldset">
              <FormLabel>Filtre por preço</FormLabel>
              <RadioGroup
                aria-label="price"
                defaultValue="0"
                name="radio-buttons-group"
                value={filter}
                onChange={(_, value) => setFilter(value)}
              >
                <FormControlLabel
                  value="0-40"
                  control={<Radio />}
                  label="Até 40"
                />
                <FormControlLabel
                  value="40-60"
                  control={<Radio />}
                  label="40 A 60"
                />
                <FormControlLabel
                  value="60-100"
                  control={<Radio />}
                  label="60 A 100"
                />
                <FormControlLabel
                  value="100-200"
                  control={<Radio />}
                  label="100-200"
                />

                <FormControlLabel
                  value="200-500"
                  control={<Radio />}
                  label="200 A 500"
                />
                <FormControlLabel
                  value="500-10000"
                  control={<Radio />}
                  label="Acima de 500"
                />
              </RadioGroup>
            </FormControl>
          </FilterContainer>
          <WineContainer>
            <NumberOfProducts>
              <Highlight>{data?.totalItems}</Highlight>
              Produtos encontrados
            </NumberOfProducts>
            {(data as Response).totalItems > 0 ? (
              <>
                <Cards>
                  {data?.items?.map((item) => (
                    <WineCard
                      id={item.id}
                      key={item.id}
                      name={item.name}
                      image={item.image}
                      price={item.price}
                      discount={item.discount}
                      priceMember={item.priceMember}
                      priceNoMember={item.priceNonMember}
                    />
                  ))}
                </Cards>
                <ButtonsContainer>
                  <Button onClick={getPreviousPage} disabled={page === 1}>
                    <HiChevronLeft />
                  </Button>
                  <PageContainer>
                    <NumberPage>{page}</NumberPage>
                  </PageContainer>
                  <Button
                    onClick={getNextPage}
                    disabled={page === data?.totalPages}
                  >
                    <HiChevronRight />
                  </Button>
                </ButtonsContainer>
              </>
            ) : (
              <ErrorTextContainer>
                <ErrorText>Nenhum produto foi encontrado.</ErrorText>
              </ErrorTextContainer>
            )}
          </WineContainer>
        </main>
      )}
    </Container>
  );
};

export default Home;
