import Head from "next/head";
import { HeaderComponent } from "../components/Header/index";
import { useState } from "react";
import WineCard from "../components/WineCard/index";
import { HiChevronRight, HiChevronLeft } from "react-icons/hi";
// import Filters from "../components/Filters";
import { Button } from "../components/ChangePageButton/styles";
import Loading from "../components/Loading/index";

import Radio from "@mui/material/Radio";
import RadioGroup from "@mui/material/RadioGroup";
import FormControlLabel from "@mui/material/FormControlLabel";
import FormControl from "@mui/material/FormControl";
import FormLabel from "@mui/material/FormLabel";

import {
  Container,
  WineContainer,
  FilterContainer,
  ButtonsContainer,
  PageContainer,
  NumberPage,
} from "../styles/HomeStyles";
import { useWineItems } from "../hooks/queries";

const limit = 9;

const Home = (): JSX.Element => {
  const [filter, setFilter] = useState("");
  const [name, setName] = useState("");
  const [page, setPage] = useState(1);

  const { data, status } = useWineItems({ filter, limit, name, page });

  const getNextPage = () => {
    if (data?.totalPages === page) {
      return;
    }
    setPage(page + 1);
  };

  const getPreviousPage = () => {
    if (page === 1) {
    }
    setPage(page - 1);
  };

  return (
    <Container>
      <Head>
        <title>Wines</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <HeaderComponent />

      {(status === "loading" || status === "idle") && (
        <div>
          <h2>Loading...</h2>
          <Loading />
        </div>
      )}

      {status === "error" && (
        <div className="message">
          <h3>Erro</h3>
        </div>
      )}

      {status === "success" && (
        <main>
          <FilterContainer></FilterContainer>
          <WineContainer>
            <div>{data?.totalItems}Produtos encontrados</div>
            <div className="cards">
              {data?.items.map((item) => {
                return (
                  <>
                    <WineCard
                      id={item.id}
                      key={item.id}
                      name={item.name}
                      image={item.image}
                      price={item.price}
                      discount={item.discount}
                      priceMember={item.priceMember}
                      priceNoMember={item.priceNonMember}
                    />
                  </>
                );
              })}
            </div>
            <ButtonsContainer>
              <Button onClick={getPreviousPage} disabled={page === 1}>
                <HiChevronLeft />
              </Button>
              <PageContainer>
                <NumberPage>{page}</NumberPage>
              </PageContainer>
              <Button
                onClick={getNextPage}
                disabled={page === data?.totalPages}
              >
                <HiChevronRight />
              </Button>
            </ButtonsContainer>
          </WineContainer>
        </main>
      )}
    </Container>
  );
};

export default Home;
