import type { NextPage } from "next";
import Head from "next/head";
import { HeaderComponent } from "../components/Header";
import { useEffect, useState } from "react";
import { getWine } from "./services/api-request";
import WineCard from "../components/WineCard/index";

import {
  Container,
  WineContainer,
  FilterContainer,
} from "../styles/HomeStyles";
interface WineItem {
  id: number;
  image: string;
  name: string;
  price: number;
  discount: number;
  priceMember: number;
  priceNonMember: number;
  type: string;
  classification: string;
  size: number;
  rating: number;
  avaliations: number;
  country: string;
  region: string;
  flag: string;
  sommelierComment: string;
}

const Home: NextPage = () => {
  const [wineItems, setWineItems] = useState<WineItem[]>([]);
  const [page, setPage] = useState(1);
  const limit = 9;

  useEffect(() => {
    const getData = async () => {
      const data = await getWine(page, limit);
      console.log(data.items);
      setWineItems(data.items);
    };
    getData();
  }, [page, limit]);

  return (
    <Container>
      <Head>
        <title>Wine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderComponent />

      <main>
        <FilterContainer>
          <></>
        </FilterContainer>
        <WineContainer>
          <div>{wineItems.length}Produtos encontrados</div>
          <div className="cards">
            {wineItems.map((item) => {
              return (
                <>
                  <WineCard
                    key={item.id}
                    name={item.name}
                    image={item.image}
                    price={item.price}
                    discount={item.discount}
                    priceMember={item.priceMember}
                    priceNoMember={item.priceNonMember}
                  />
                </>
              );
            })}
          </div>
        </WineContainer>
      </main>
    </Container>
  );
};

export default Home;
