import type { NextPage } from "next";
import Head from "next/head";
import { HeaderComponent } from "../components/Header";
import { useEffect, useState } from "react";
import { getWine } from "./services/api-request";
import WineCard from "../components/WineCard/index";
import { HiChevronRight, HiChevronLeft } from "react-icons/hi";

import {
  Container,
  WineContainer,
  FilterContainer,
  ButtonsContainer,
} from "../styles/HomeStyles";
import { Button } from "../components/ChangePageButton/index/styles";

interface RequestProps {
  page: number;
  totalPages: number;
  itemsPerPage: number;
  totalItems: number;
}
interface WineItem {
  id: number;
  image: string;
  name: string;
  price: number;
  discount: number;
  priceMember: number;
  priceNonMember: number;
  type: string;
  classification: string;
  size: number;
  rating: number;
  avaliations: number;
  country: string;
  region: string;
  flag: string;
  sommelierComment: string;
}

const next = "next";

const Home: NextPage = () => {
  const [requestData, setRequestData] = useState<RequestProps>({
    page: 0,
    totalPages: 0,
    itemsPerPage: 0,
    totalItems: 0,
  });
  const [wineItems, setWineItems] = useState<WineItem[]>([]);
  const [page, setPage] = useState(1);
  const limit = 9;

  useEffect(() => {
    const getData = async () => {
      const data = await getWine(page, limit);
      setRequestData(data);
      setWineItems(data.items);
    };
    getData();
  }, [page, limit]);

  const getNextPage = () => {
    if (requestData.totalPages === page) {
      return;
    }
    setPage(page + 1);
  };

  const getPreviousPage = () => {
    if (page === 1) {
      return;
    }
    setPage(page - 1);
  };

  return (
    <Container>
      <Head>
        <title>Wine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderComponent />

      <main>
        <FilterContainer>
          <></>
        </FilterContainer>
        <WineContainer>
          <div>{requestData.totalItems}Produtos encontrados</div>
          <div className="cards">
            {wineItems.map((item) => {
              return (
                <>
                  <WineCard
                    key={item.id}
                    name={item.name}
                    image={item.image}
                    price={item.price}
                    discount={item.discount}
                    priceMember={item.priceMember}
                    priceNoMember={item.priceNonMember}
                  />
                </>
              );
            })}
          </div>
          <ButtonsContainer>
            <Button onClick={getPreviousPage} disabled={page === 1}>
              <HiChevronLeft />
            </Button>
            <div>
              <span>{page}</span>
            </div>
            <Button
              onClick={getNextPage}
              disabled={requestData.totalPages === page}
            >
              <HiChevronRight />
            </Button>
          </ButtonsContainer>
        </WineContainer>
      </main>
    </Container>
  );
};

export default Home;
